# Generated by Django 2.2.5 on 2021-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploader',
            name='slug',
        ),
        migrations.AddField(
            model_name='uploader',
            name='file_details',
            field=models.TextField(default=1, verbose_name='Put Your Files Detials?'),
            preserve_default=False,
        ),
    ]
